#!/usr/bin/env python3
"""
Build script to generate contracts.py from MASS_CONTRACTS directory.
This replaces runtime file loading with build-time constants.
"""

import os
import json
import sys
from pathlib import Path


def generate_contracts_module(contracts_path: str, output_path: str):
    """Generate a Python module with contract addresses and ABIs as constants."""

    contracts_dir = Path(contracts_path)
    if not contracts_dir.exists():
        raise FileNotFoundError(f"Contracts directory not found: {contracts_path}")

    # Load deployment addresses
    addresses_file = contracts_dir / "deploymentAddresses.json"
    if not addresses_file.exists():
        raise FileNotFoundError(
            f"Deployment addresses file not found: {addresses_file}"
        )

    with open(addresses_file, "r") as f:
        addresses = json.load(f)

    # Load ABI files
    abi_dir = contracts_dir / "abi"
    if not abi_dir.exists():
        raise FileNotFoundError(f"ABI directory not found: {abi_dir}")

    required_abis = [
        "RelayReg.json",
        "ShopReg.json",
        "Eddies.json",
        "PaymentsByAddress.json",
    ]
    abis = {}

    for abi_file in required_abis:
        abi_path = abi_dir / abi_file
        if not abi_path.exists():
            raise FileNotFoundError(f"ABI file not found: {abi_path}")

        with open(abi_path, "r") as f:
            contract_name = abi_file.replace(".json", "")
            abis[contract_name] = f.read()

    # Generate Python module content
    module_content = f'''# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

"""
Generated contract constants from MASS_CONTRACTS directory.
This file is auto-generated by generate_contracts.py - do not edit manually.

Original MASS_CONTRACTS path: {contracts_path}
"""

# Contract deployment addresses
DEPLOYMENT_ADDRESSES = {json.dumps(addresses, indent=4)}

# Contract ABIs
RELAY_REG_ABI = {repr(abis["RelayReg"])}

SHOP_REG_ABI = {repr(abis["ShopReg"])}

EDDIES_ABI = {repr(abis["Eddies"])}

PAYMENTS_BY_ADDRESS_ABI = {repr(abis["PaymentsByAddress"])}

# Convenience mapping for easy access
ABIS = {{
    "RelayReg": RELAY_REG_ABI,
    "ShopReg": SHOP_REG_ABI,
    "Eddies": EDDIES_ABI,
    "PaymentsByAddress": PAYMENTS_BY_ADDRESS_ABI,
}}
'''

    # Write the generated module
    with open(output_path, "w") as f:
        f.write(module_content)

    print(f"Generated contracts module: {output_path}")
    print(f"Contract addresses: {list(addresses.keys())}")
    print(f"Contract ABIs: {list(abis.keys())}")


def main():
    """Main entry point for the build script."""
    contracts_path = os.getenv("MASS_CONTRACTS")
    if not contracts_path:
        print("Error: MASS_CONTRACTS environment variable not set", file=sys.stderr)
        sys.exit(1)

    # Default output path - same directory as this script
    script_dir = Path(__file__).parent
    output_path = script_dir / "massmarket_client" / "contracts.py"

    # Allow override via command line argument
    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])

    try:
        generate_contracts_module(contracts_path, output_path)
        print(f"Successfully generated {output_path}")
    except Exception as e:
        print(f"Error generating contracts module: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
