# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

name: test
on: [push]
jobs:
  pystoretest-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check linting
        run: nix develop -c make lint

      - name: Client import check
        run: |
          nix develop -c python -c "
          # Test main client imports
          from massmarket_client import RelayClientProtocol
          from massmarket_client.legacy_client import RelayClient as LegacyRelayClient
          from massmarket_client.client import RefactoredRelayClient

          
          print('✅ All client imports successful')
          print(f'✅ RelayClientProtocol: {RelayClientProtocol}')
          print(f'✅ LegacyRelayClient: {LegacyRelayClient}') 
          print(f'✅ RefactoredRelayClient: {RefactoredRelayClient}')
          "
